version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
      - linters:
          - unparam
          - unused
        path: mock_
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/entire-vc/evc-mesh
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
