/**
 * The cross-implementation anchor contract, frontend side.
 *
 * The frontend and the Go server both turn a piece of text into a comment
 * anchor — this side from a mouse selection, the server side from a quote an
 * agent sent, because an agent has no selection to measure. They have to produce
 * the same anchor for the same words.
 *
 * When they do not, nothing reports an error. A comment left by an agent and a
 * comment left by a person, on the same sentence, simply point at different
 * text. That is the failure this file exists to make loud, and it is the one
 * failure neither implementation can catch on its own, because each is perfectly
 * self-consistent.
 *
 * ## How the pair works
 *
 * - `scripts/anchor-contract/cases.json` — the inputs. A document body, the
 *   plain text a reader sees, and the run of it a reader selects.
 * - `internal/textanchor/testdata/frontend-anchors.json` — what THIS module
 *   answers for them, generated by this same file under `ANCHOR_WRITE=1`
 *   (`scripts/anchor-contract/regenerate.sh`).
 * - this test asserts the frontend still answers that;
 *   `TestContract_ServerAndFrontendAgreeOnTheSameSelection` (Go) asserts the
 *   server reaches the same offsets from the quote alone.
 *
 * Generator and assertion are one file on purpose. Two files would be two
 * spellings of "run the builder over the cases", and the day they drifted the
 * fixture would be regenerated by code that is not the code being checked.
 *
 * So: change the resolution rules here and this goes red. Change them in Go and
 * the Go test goes red. Change both to agree and both stay green — which is the
 * only outcome that should be quiet.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { buildAnchorFromSelection } from "../anchor";

interface Case {
  name: string;
  why: string;
  source: string;
  rendered: string;
  select: string;
  /** Which occurrence of `select` to take, 1-based. Default 1. */
  occurrence?: number;
}

interface ExpectedAnchor {
  name: string;
  why: string;
  exact: string;
  prefix: string;
  suffix: string;
  start: number;
  end: number;
}

// vitest runs with the web package as its root; the contract spans the repo.
const repoRoot = resolve(process.cwd(), "..");
const casesPath = resolve(repoRoot, "scripts/anchor-contract/cases.json");
const fixturePath = resolve(repoRoot, "internal/textanchor/testdata/frontend-anchors.json");

const cases = (JSON.parse(readFileSync(casesPath, "utf8")) as { cases: Case[] }).cases;

/** The selection a case describes, as a span of the rendered text. */
function spanOf(testCase: Case): { start: number; end: number } {
  const wanted = testCase.occurrence ?? 1;
  let start = -1;
  for (let n = 0; n < wanted; n++) {
    start = testCase.rendered.indexOf(testCase.select, start + 1);
    if (start < 0) {
      throw new Error(
        `case ${testCase.name}: "select" does not occur ${wanted} time(s) in "rendered"`,
      );
    }
  }
  return { start, end: start + testCase.select.length };
}

/** What this module answers for a case. */
function anchorFor(testCase: Case): ExpectedAnchor {
  const built = buildAnchorFromSelection(testCase.source, testCase.rendered, spanOf(testCase));
  if (!built) throw new Error(`case ${testCase.name}: no anchor was built`);
  if (built.unplaceable) {
    throw new Error(
      `case ${testCase.name}: the quote could not be placed in the source, so the case ` +
        `would assert nothing`,
    );
  }
  const { exact, prefix, suffix, start, end } = built.anchor;
  if (start === null || end === null) {
    throw new Error(`case ${testCase.name}: the anchor carries no offsets`);
  }
  return { name: testCase.name, why: testCase.why, exact, prefix, suffix, start, end };
}

describe("anchor contract", () => {
  if (process.env.ANCHOR_WRITE === "1") {
    // Regeneration mode. Deliberately an `it` rather than a script entry point:
    // the fixture must be written by the same code path that asserts against it.
    it("writes the fixture", () => {
      const anchors = cases.map(anchorFor);
      writeFileSync(
        fixturePath,
        `${JSON.stringify(
          {
            note:
              "GENERATED — do not hand-edit. Anchors produced by " +
              "web/src/lib/doc-comments/anchor.ts (buildAnchorFromSelection) over " +
              "scripts/anchor-contract/cases.json. Regenerate with " +
              "scripts/anchor-contract/regenerate.sh.",
            generated_from: { module: "web/src/lib/doc-comments/anchor.ts" },
            anchors,
          },
          null,
          2,
        )}\n`,
        "utf8",
      );
      expect(anchors.length).toBe(cases.length);
    });
    return;
  }

  const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as { anchors: ExpectedAnchor[] };

  it("covers every case", () => {
    expect(fixture.anchors.map((a) => a.name)).toEqual(cases.map((c) => c.name));
  });

  for (const testCase of cases) {
    it(`still anchors ${testCase.name} the way the server expects`, () => {
      const expected = fixture.anchors.find((a) => a.name === testCase.name);
      expect(expected, `no recorded anchor for ${testCase.name}`).toBeDefined();

      const got = anchorFor(testCase);
      expect({ start: got.start, end: got.end, exact: got.exact }).toEqual({
        start: expected!.start,
        end: expected!.end,
        exact: expected!.exact,
      });
      expect(got.prefix).toBe(expected!.prefix);
      expect(got.suffix).toBe(expected!.suffix);
    });
  }

  // The negative control for the fixture itself. On ASCII a byte offset and a
  // character offset are the same number, so an all-ASCII contract agrees no
  // matter which coordinate system either side uses — it is green and it proves
  // nothing. This is the assertion that the cases can actually tell them apart.
  it("has cases where a byte offset is not a character offset", () => {
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();

    const discriminating = fixture.anchors.filter((anchor) => {
      const source = cases.find((c) => c.name === anchor.name)!.source;
      // The same position expressed the way JavaScript would count it: the number
      // of UTF-16 units before it. Decoding the byte prefix is the only honest way
      // to get that — slicing the string by a byte offset is exactly the bug.
      const units = decoder.decode(encoder.encode(source).slice(0, anchor.start)).length;
      return units !== anchor.start;
    });
    expect(discriminating.length).toBeGreaterThanOrEqual(7);
  });
});
