package textanchor

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The cross-implementation contract: an anchor this package computes from a quote
// and an anchor the FRONTEND computes from a mouse selection over the same words
// must be the same anchor.
//
// This is the most valuable test in the package, because it is the only one that
// can fail when both implementations are individually self-consistent and
// disagree with each other. That failure is the one that hurts: a comment left by
// an agent and a comment left by a person, on the same sentence, pointing at
// different text — with nothing anywhere reporting an error.
//
// # What the fixture is, and what it is not
//
// testdata/frontend-anchors.json is GENERATED by running the real frontend module
// (web/src/lib/doc-comments/anchor.ts, buildAnchorFromSelection) over
// scripts/anchor-contract/cases.json — see scripts/anchor-contract/regenerate.sh.
// It is not a table of numbers written out by hand from reading the TypeScript;
// that would only prove the two were typed to agree once.
//
// Both halves assert against it, so neither side can drift quietly: this test
// checks the server reaches those offsets from the quote alone, and
// web/src/lib/doc-comments/__tests__/anchor-contract.test.ts checks the frontend
// still produces them from the selection. Changing the resolution rules on one
// side reddens that side's own build; changing both to agree is the only quiet
// outcome, which is the point.
//
// The bound worth stating: the contract covers the cases in cases.json and
// nothing else. It is a discrimination test, not a proof of equivalence — add a
// case when a new class of document shows up (a table, a footnote, a nested
// list), because a class with no case in it is a class where the two are free to
// disagree.
//
// One case in particular is weaker than its name suggests: combining-accent
// selects a whole intact glyph, so it checks that neither side splits one by
// accident — it does NOT exercise rejecting a match that starts mid-cluster.
// That is server-only behaviour (the frontend snaps, the server refuses) and it
// lives in TestResolve_OffsetsNeverLandInsideACombiningSequence, not here.
type contractAnchor struct {
	Name   string `json:"name"`
	Why    string `json:"why"`
	Exact  string `json:"exact"`
	Prefix string `json:"prefix"`
	Suffix string `json:"suffix"`
	Start  int    `json:"start"`
	End    int    `json:"end"`
}

type contractCase struct {
	Name       string `json:"name"`
	Why        string `json:"why"`
	Source     string `json:"source"`
	Rendered   string `json:"rendered"`
	Select     string `json:"select"`
	Occurrence int    `json:"occurrence"`
}

func loadContract(t *testing.T) (anchors []contractAnchor, cases map[string]contractCase, module string) {
	t.Helper()

	var fixture struct {
		GeneratedFrom struct {
			Module string `json:"module"`
		} `json:"generated_from"`
		Anchors []contractAnchor `json:"anchors"`
	}
	raw, err := os.ReadFile(filepath.Join("testdata", "frontend-anchors.json"))
	require.NoError(t, err, "regenerate with scripts/anchor-contract/regenerate.sh")
	require.NoError(t, json.Unmarshal(raw, &fixture))

	var spec struct {
		Cases []contractCase `json:"cases"`
	}
	raw, err = os.ReadFile(filepath.Join("..", "..", "scripts", "anchor-contract", "cases.json"))
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(raw, &spec))

	cases = make(map[string]contractCase, len(spec.Cases))
	for _, c := range spec.Cases {
		cases[c.Name] = c
	}

	require.NotEmpty(t, fixture.Anchors)
	require.Len(t, fixture.Anchors, len(spec.Cases),
		"the fixture is stale: it does not cover every case — regenerate it")

	return fixture.Anchors, cases, fixture.GeneratedFrom.Module
}

// TestContract_ServerAndFrontendAgreeOnTheSameSelection is AC4.
func TestContract_ServerAndFrontendAgreeOnTheSameSelection(t *testing.T) {
	anchors, cases, module := loadContract(t)
	t.Logf("frontend anchors generated from %s", module)

	for _, want := range anchors {
		t.Run(want.Name, func(t *testing.T) {
			testCase, ok := cases[want.Name]
			require.True(t, ok, "no case named %q in cases.json", want.Name)
			t.Log(want.Why)

			// The server is given only what an agent could send: the quote, and the
			// text around it. It is NOT given the offsets it is being asked to
			// reproduce — that is the whole content of the assertion.
			got, err := Resolve(testCase.Source, want.Exact, Context{
				Prefix: want.Prefix,
				Suffix: want.Suffix,
			})
			require.NoError(t, err)

			assert.Equal(t, want.Start, got.Start,
				"server and frontend disagree about where this quote starts")
			assert.Equal(t, want.End, got.End,
				"server and frontend disagree about where this quote ends")

			// Same offsets is the contract; this says what the offsets have to mean,
			// so a pair that agreed on a wrong number would still be caught.
			assert.True(t, SpanMatchesQuote(testCase.Source, Span{Start: got.Start, End: got.End}, want.Exact),
				"the agreed offsets do not point at the quote: %q", testCase.Source[got.Start:got.End])
		})
	}
}

// TestContract_FixtureDistinguishesTheCoordinateSystems is the negative control
// for the contract suite itself.
//
// A cross-implementation test on ASCII text agrees no matter which coordinate
// system either side uses, because on ASCII they are the same number. Without
// this, "server and frontend agree" could be true of two implementations that
// disagree with each other on every Russian document in the workspace — which is
// the state of the world this whole unit exists to prevent.
func TestContract_FixtureDistinguishesTheCoordinateSystems(t *testing.T) {
	anchors, cases, _ := loadContract(t)

	discriminating := 0
	for _, anchor := range anchors {
		source := cases[anchor.Name].Source
		require.NotEmpty(t, source)

		byteStart := anchor.Start
		charStart := utf8.RuneCountInString(source[:byteStart])
		if byteStart != charStart {
			discriminating++
			continue
		}
		assert.Equal(t, "ascii-control", anchor.Name,
			"case %q sits in an all-ASCII prefix, so it cannot tell a byte offset from a "+
				"character offset and proves nothing; give it non-ASCII text before the selection",
			anchor.Name)
	}

	assert.GreaterOrEqual(t, discriminating, 7,
		"too few cases can actually distinguish byte offsets from character offsets")
}

// TestContract_QuoteAndRawSliceDifferAcrossMarkup pins the property AC5 is about,
// on the generated fixture rather than on a hand-written example: for a selection
// that crossed inline markup the stored quote is NOT the raw slice, and both
// implementations agree on that same wider span.
func TestContract_QuoteAndRawSliceDifferAcrossMarkup(t *testing.T) {
	anchors, cases, _ := loadContract(t)

	markupCases := 0
	for _, anchor := range anchors {
		source := cases[anchor.Name].Source
		slice := source[anchor.Start:anchor.End]
		if slice == anchor.Exact {
			continue
		}
		markupCases++
		// Never shorter: the slice is the quote plus whatever source-only syntax the
		// selection crossed. Equal length is the soft-line-break case, where a
		// newline in the source stands for one space in the rendered text.
		assert.GreaterOrEqual(t, len(slice), len(anchor.Exact),
			"case %q: the raw slice cannot be shorter than the quote it contains", anchor.Name)
		assert.True(t, SpanMatchesQuote(source, Span{Start: anchor.Start, End: anchor.End}, anchor.Exact),
			"case %q: the markup-tolerant invariant has to hold where plain equality does not", anchor.Name)
		assert.True(t, strings.ContainsAny(slice, "*[]()\n"),
			"case %q: the slice differs from the quote but carries no markup and no line break — "+
				"that is a mismatch, not markup tolerance", anchor.Name)
	}

	assert.GreaterOrEqual(t, markupCases, 3,
		"the fixture no longer covers selections spanning markup")
}
