package service

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
)

// Agent API keys are 24 bytes from crypto/rand rendered as hex — 192 bits of
// entropy, generated by the server, never chosen by a person. bcrypt's work
// factor exists to make a dictionary attack on a human-chosen password
// expensive; against a 192-bit random secret there is no dictionary, so the
// factor buys nothing except ~163 ms of CPU on every request that presents a
// key.
//
// The standard construction for verifying a high-entropy bearer token is a
// single keyed hash plus a constant-time comparison, which is what this file
// provides. bcrypt remains the stored source of truth (see agent_service.go);
// this is the fast path layered over it.

// agentKeyDigestLabel is HMAC's key here, and it is deliberately a constant
// rather than a secret.
//
// A server-side pepper would buy one property: a database dump alone could not
// be used to forge a digest. It would also make the pepper a credential whose
// loss or rotation silently invalidates every agent key in the fleet at once —
// a digest computed under the old pepper is indistinguishable from a wrong key,
// so there is no way to fall back safely, and the operator's remedy would be to
// re-issue every key. For a self-hosted product that is a worse failure than
// the one it prevents, and it prevents little: forging a digest still requires
// the 192-bit key, which the dump does not contain (the bcrypt column does not
// yield it either).
//
// So the key here is a fixed domain-separation label. It keeps the construction
// HMAC rather than a bare hash, which is the right shape if a secret is ever
// introduced deliberately, and costs nothing.
var agentKeyDigestLabel = []byte("evc-mesh/agent-api-key/v1")

// agentKeyDigest returns the hex-encoded HMAC-SHA256 of rawKey.
//
// Hex rather than base64 because the value lands in a TEXT column that people
// read in psql, and hex has no encoding variants to get wrong.
func agentKeyDigest(rawKey string) string {
	mac := hmac.New(sha256.New, agentKeyDigestLabel)
	mac.Write([]byte(rawKey))
	return hex.EncodeToString(mac.Sum(nil))
}

// agentKeyDigestMatches reports whether rawKey hashes to storedDigest.
//
// An empty storedDigest is never a match: it means the row predates the fast
// path and the caller must fall back to bcrypt. Returning true there would turn
// "we have not computed this yet" into "any key is accepted".
//
// The comparison is constant-time. The digest of a wrong key is uncorrelated
// with the right one, so a length-or-prefix leak here is not obviously
// exploitable — but "not obviously" is not a reason to hand-roll the fast
// version of a credential check.
func agentKeyDigestMatches(storedDigest, rawKey string) bool {
	if storedDigest == "" {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(storedDigest), []byte(agentKeyDigest(rawKey))) == 1
}
