package service

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
)

// Agent API keys are 24 bytes from crypto/rand rendered as hex — 192 bits of
// entropy, generated by the server, never chosen by a person. bcrypt's work
// factor exists to make a dictionary attack on a human-chosen password
// expensive; against a 192-bit random secret there is no dictionary, so the
// factor buys nothing except ~163 ms of CPU on every request that presents a
// key.
//
// The standard construction for verifying a high-entropy bearer token is a
// single keyed hash plus a constant-time comparison, which is what this file
// provides. bcrypt remains the stored source of truth (see agent_service.go);
// this is the fast path layered over it.

// agentKeyDigestLabel is HMAC's key here, and it is deliberately a constant
// rather than a secret.
//
// A server-side pepper would buy one property: a database dump alone could not
// be used to forge a digest. It would also make the pepper a credential whose
// loss or rotation silently invalidates every agent key in the fleet at once —
// a digest computed under the old pepper is indistinguishable from a wrong key,
// so there is no way to fall back safely, and the operator's remedy would be to
// re-issue every key. For a self-hosted product that is a worse failure than
// the one it prevents, and it prevents little: forging a digest still requires
// the 192-bit key, which the dump does not contain (the bcrypt column does not
// yield it either).
//
// So the key here is a fixed domain-separation label. It keeps the construction
// HMAC rather than a bare hash, which is the right shape if a secret is ever
// introduced deliberately, and costs nothing.
var agentKeyDigestLabel = []byte("evc-mesh/agent-api-key/v1")

// agentKeyDigest returns the hex-encoded HMAC-SHA256 of rawKey.
//
// Hex rather than base64 because the value lands in a TEXT column that people
// read in psql, and hex has no encoding variants to get wrong.
func agentKeyDigest(rawKey string) string {
	mac := hmac.New(sha256.New, agentKeyDigestLabel)
	mac.Write([]byte(rawKey))
	return hex.EncodeToString(mac.Sum(nil))
}

// agentKeyDigestMatches reports whether rawKey hashes to storedDigest.
//
// An empty storedDigest is never a match: it means the row predates the fast
// path and the caller must fall back to bcrypt. Returning true there would turn
// "we have not computed this yet" into "any key is accepted".
//
// The comparison is constant-time. The digest of a wrong key is uncorrelated
// with the right one, so a length-or-prefix leak here is not obviously
// exploitable — but "not obviously" is not a reason to hand-roll the fast
// version of a credential check.
func agentKeyDigestMatches(storedDigest, rawKey string) bool {
	if storedDigest == "" {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(storedDigest), []byte(agentKeyDigest(rawKey))) == 1
}

// bcryptMaxInputBytes is bcrypt's own hard input cap — golang.org/x/crypto/
// bcrypt.GenerateFromPassword returns a bare error (not a truncation) past
// this length. Verified empirically against the vendored version: 72 bytes
// succeeds, 73 fails with "password length exceeds 72 bytes".
const bcryptMaxInputBytes = 72

// bcryptInput returns the bytes bcrypt should hash or compare for an agent
// API key, correcting for bcryptMaxInputBytes.
//
// An agent key's length is not fixed — it embeds the workspace slug
// (agk_{slug}_{48 hex}) — so a long enough slug (empirically: >19 chars; the
// fixed agk_/_/48-hex overhead is 53 bytes) pushes the whole key past the cap
// and bcrypt.GenerateFromPassword returns a bare error instead of truncating
// (#9317fcd0 — measured live: POST /workspaces/:ws/agents and
// .../agent-grants both 500'd on a 27-char slug).
//
// Below the cap, rawKey passes through unchanged. That is the path every
// already-issued key in the fleet uses today — workspace slugs have stayed
// under the cap by convention, not by any enforced check — so this change
// alters nothing about verifying an existing hash.
//
// At or above the cap, agentKeyDigest's fixed 64-byte hex output stands in
// for the key instead. This loses no security: it is a keyed hash of the
// SAME 192-bit random secret (see agentKeyDigest's own doc for why bcrypt's
// cost factor buys nothing against a server-generated random key in the
// first place), and which representation to use is a PURE function of
// len(rawKey) — recomputed identically at generation and at every future
// verification of that same key, with no flag to store and nothing to
// migrate.
//
// MUST be called at every bcrypt.GenerateFromPassword/CompareHashAndPassword
// site that touches an agent API key (agent_service.go,
// agent_workspace_grant_service.go) — an inconsistent call site would be
// unable to verify keys the others generate.
func bcryptInput(rawKey string) []byte {
	if len(rawKey) > bcryptMaxInputBytes {
		return []byte(agentKeyDigest(rawKey))
	}
	return []byte(rawKey)
}
