#!/bin/sh
# Renders the trusted-hop list that nginx.conf includes for its realip module.
#
# Runs from /docker-entrypoint.d/ on every container start (the stock nginx
# entrypoint executes these in name order), and once at image build so the
# image carries a working default and `nginx -t` passes without it.
#
# The trust set is the SAME one mesh-api uses (MESH_TRUSTED_PROXIES, "in
# addition to loopback / link-local / private ranges" — see cmd/api/main.go),
# so one variable defines one boundary for both services. Two different
# trust boundaries on one request path is how the per-IP limiters were
# silently unkeyed before (#5d759aad, #358a35dc).
#
# Fail closed: a malformed entry stops the container rather than being
# dropped, because a dropped entry means an edge you thought was trusted
# is not, and every client then shares the edge's address as one bucket.
set -eu

OUT=${MESH_TRUSTED_PROXIES_OUT:-/etc/nginx/mesh-trusted-proxies.conf}

# Same families Echo trusts by default in mesh-api: loopback, link-local,
# private (RFC 1918 + ULA).
DEFAULTS="127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 169.254.0.0/16 ::1/128 fc00::/7 fe80::/10"

set -f # entries are CIDRs, never globs
EXTRA=$(printf '%s' "${MESH_TRUSTED_PROXIES:-}" | tr ',' ' ')

TMP="$OUT.tmp"
{
  echo "# Generated by 25-mesh-trusted-proxies.sh — do not edit; set MESH_TRUSTED_PROXIES."
  for cidr in $DEFAULTS $EXTRA; do
    # Whitelist of characters legal in an IPv4/IPv6 address or CIDR. Anything
    # else (';', '}', whitespace, quotes) would be nginx config injection. An
    # entry without ':' is IPv4 and may hold only digits and dots — that also
    # keeps hex-looking hostnames ('abc.def') from reaching nginx, which would
    # resolve and trust them.
    case $cidr in
      *[!0-9a-fA-F:./]*)
        echo "$0: refusing MESH_TRUSTED_PROXIES entry '$cidr': not an IP address or CIDR" >&2
        exit 1
        ;;
      *:*) ;;
      *[!0-9./]*)
        echo "$0: refusing MESH_TRUSTED_PROXIES entry '$cidr': not an IPv4 address or CIDR" >&2
        exit 1
        ;;
    esac
    # mesh-api parses this same variable with net.ParseCIDR and drops a bare
    # address (with a log line), while nginx would accept it — one entry then
    # means two different boundaries. Require the prefix length here too, and
    # refuse /0 (in any spelling): it trusts every client, which switches the protection off.
    case $cidr in
      */0*)
        # Any prefix starting with 0, not just "/0": /00 and /000 parse to /0 in
        # both nginx and Go, and a legitimate prefix never has a leading zero.
        echo "$0: refusing MESH_TRUSTED_PROXIES entry '$cidr': a /0 (or zero-led) prefix trusts every client" >&2
        exit 1
        ;;
      */*) ;;
      *)
        echo "$0: refusing MESH_TRUSTED_PROXIES entry '$cidr': give a CIDR with a prefix length (/32 or /128 for a single host)" >&2
        exit 1
        ;;
    esac
    echo "set_real_ip_from $cidr;"
  done
} >"$TMP"
mv "$TMP" "$OUT"

if [ -n "$EXTRA" ]; then
  echo "$0: trusting X-Forwarded-For from the default private ranges plus: $EXTRA" >&2
else
  echo "$0: trusting X-Forwarded-For only from loopback/link-local/private ranges" >&2
fi
