//go:build integration

package postgres

import (
	"context"
	"database/sql"
	"os"
	"path/filepath"
	"testing"

	"github.com/jmoiron/sqlx"
	"github.com/pressly/goose/v3"
	"github.com/stretchr/testify/require"
)

// TestParkedWaitMigrationDownUpIsolated exercises only this migration in a
// dedicated schema. The advisory lock protects the fixed schema name if two
// copies of the integration suite share a PostgreSQL service.
func TestParkedWaitMigrationDownUpIsolated(t *testing.T) {
	lockDB := testDB(t)
	var migrationDB *sqlx.DB
	lock, err := lockDB.BeginTxx(context.Background(), nil)
	require.NoError(t, err)
	_, err = lock.Exec(`SELECT pg_advisory_xact_lock(90304261007004)`)
	require.NoError(t, err)
	t.Cleanup(func() {
		if migrationDB != nil {
			_ = migrationDB.Close()
		}
		if _, cleanupErr := lockDB.Exec(`DROP SCHEMA IF EXISTS parked_wait_migration_test CASCADE`); cleanupErr != nil {
			t.Errorf("drop isolated parked-wait migration schema: %v", cleanupErr)
		}
		if cleanupErr := lock.Rollback(); cleanupErr != nil && cleanupErr != sql.ErrTxDone {
			t.Errorf("release isolated migration test lock: %v", cleanupErr)
		}
	})

	_, err = lockDB.Exec(`DROP SCHEMA IF EXISTS parked_wait_migration_test CASCADE; CREATE SCHEMA parked_wait_migration_test`)
	require.NoError(t, err)

	migrationDB = testDB(t)
	migrationDB.SetMaxOpenConns(1)
	_, err = migrationDB.Exec(`SELECT set_config('search_path', 'parked_wait_migration_test,public', false)`)
	require.NoError(t, err)
	_, err = migrationDB.Exec(`
		CREATE TYPE actor_type AS ENUM ('agent', 'user');
		CREATE TABLE tasks (id uuid PRIMARY KEY);
		CREATE TABLE task_dependencies (id bigint PRIMARY KEY);
		CREATE FUNCTION invalidate_task_snapshot_on_activity() RETURNS trigger
			LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
		CREATE TABLE goose_db_version (
			id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
			version_id bigint NOT NULL,
			is_applied boolean NOT NULL,
			tstamp timestamp NOT NULL DEFAULT now()
		);
		INSERT INTO goose_db_version (version_id, is_applied) VALUES (20261007002, true);
	`)
	require.NoError(t, err)

	migration, err := os.ReadFile("../../../migrations/20261007003_parked_wait_release.sql")
	require.NoError(t, err)
	migrationsDir, err := os.MkdirTemp("", "parked-wait-migration-")
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(migrationsDir, "20261007003_parked_wait_release.sql"), migration, 0600))
	t.Cleanup(func() {
		if cleanupErr := os.RemoveAll(migrationsDir); cleanupErr != nil {
			t.Errorf("remove isolated migration files: %v", cleanupErr)
		}
	})
	require.NoError(t, goose.SetDialect("postgres"))
	require.NoError(t, goose.Up(migrationDB.DB, migrationsDir))
	require.EqualValues(t, 20261007003, gooseVersion(t, migrationDB.DB))
	assertParkedWaitMigrationObjects(t, migrationDB, true)

	require.NoError(t, goose.Down(migrationDB.DB, migrationsDir))
	require.EqualValues(t, 20261007002, gooseVersion(t, migrationDB.DB))
	assertParkedWaitMigrationObjects(t, migrationDB, false)

	require.NoError(t, goose.Up(migrationDB.DB, migrationsDir))
	require.EqualValues(t, 20261007003, gooseVersion(t, migrationDB.DB))
	assertParkedWaitMigrationObjects(t, migrationDB, true)
}

func assertParkedWaitMigrationObjects(t *testing.T, db *sqlx.DB, want bool) {
	t.Helper()
	var table, trigger bool
	require.NoError(t, db.Get(&table, `SELECT to_regclass('parked_wait_migration_test.parked_waits') IS NOT NULL`))
	require.NoError(t, db.Get(&trigger, `SELECT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname='dependency_task_snapshot' AND NOT tgisinternal AND tgrelid='parked_wait_migration_test.task_dependencies'::regclass)`))
	require.Equal(t, want, table, "parked_waits table presence")
	require.Equal(t, want, trigger, "dependency_task_snapshot trigger presence")
}
